[tool.poetry]
name = "nsfw"
version = "0.1.0"
description = ""
authors = ["Thomas Lee <tom@darkstarinternet.com>"]
readme = "README.md"

[tool.poetry.dependencies]
nudenet = "^3.4.2"
python = "^3.12.4"
textual = "^5.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"